step: step.c
	gcc -g3 step.c -o step

until: until.c
	gcc -g3 until.c -o until

inspect: inspect.c
	gcc -g3 inspect.c -o inspect

break: break.c break2.c
	gcc -g3 break.c break2.c -o break

trace: trace.c
	gcc -g3 trace.c -o trace

seg1: seg1.c
	gcc -g3 seg1.c -o seg1

seg2: seg2.c
	gcc -g3 seg2.c -o seg2

leak: leak.c
	gcc -g3 leak.c -o leak
